name: Linter

on: [push]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
